#' Custom ggplot2 Theme
#'
#' @export
#' @importFrom ggplot2 theme_bw theme element_text element_blank element_rect element_line margin unit
theme_pretty <- function() {
  theme_bw() +
    theme(axis.title = element_text(size = 9, color = "black"), axis.text = element_text(size = 8, color = "#333333"),
          legend.title = element_text(size = 9), legend.text = element_text(size = 8),
          text=element_text(size=8),
          panel.grid.major = element_line(color = "grey", size = 0.2),
          panel.grid.minor = element_line(color = "grey", size = 0.2),
          panel.background = element_rect(fill = "white", colour = "black",
                                          size = 0.5, linetype = "solid"),
          #plot.background = element_rect(fill = "#E8C837"),
          plot.margin = margin(t = 0, unit='cm'),
          # legend.position = c(1, 1),
          # legend.justification = c("right", "top"),
          # legend.box.just = "right",
          legend.margin =  margin(t = 0.5, b = 0.5, r = 0.5, l = 0.5, unit='cm'),
          legend.background = element_rect(fill="transparent"),
          legend.box.spacing = margin(),
          legend.key.size = unit(0.3, "cm")
    )
}




# customizable attributes
# theme(
#   line,
#   rect,
#   text,
#   title,
#   aspect.ratio,
#   axis.title,
#   axis.title.x,
#   axis.title.x.top,
#   axis.title.x.bottom,
#   axis.title.y,
#   axis.title.y.left,
#   axis.title.y.right,
#   axis.text,
#   axis.text.x,
#   axis.text.x.top,
#   axis.text.x.bottom,
#   axis.text.y,
#   axis.text.y.left,
#   axis.text.y.right,
#   axis.ticks,
#   axis.ticks.x,
#   axis.ticks.x.top,
#   axis.ticks.x.bottom,
#   axis.ticks.y,
#   axis.ticks.y.left,
#   axis.ticks.y.right,
#   axis.ticks.length,
#   axis.ticks.length.x,
#   axis.ticks.length.x.top,
#   axis.ticks.length.x.bottom,
#   axis.ticks.length.y,
#   axis.ticks.length.y.left,
#   axis.ticks.length.y.right,
#   axis.line,
#   axis.line.x,
#   axis.line.x.top,
#   axis.line.x.bottom,
#   axis.line.y,
#   axis.line.y.left,
#   axis.line.y.right,
#   legend.background,
#   legend.margin,
#   legend.spacing,
#   legend.spacing.x,
#   legend.spacing.y,
#   legend.key,
#   legend.key.size,
#   legend.key.height,
#   legend.key.width,
#   legend.text,
#   legend.text.align,
#   legend.title,
#   legend.title.align,
#   legend.position,
#   legend.direction,
#   legend.justification,
#   legend.box,
#   legend.box.just,
#   legend.box.margin,
#   legend.box.background,
#   legend.box.spacing,
#   panel.background,
#   panel.border,
#   panel.spacing,
#   panel.spacing.x,
#   panel.spacing.y,
#   panel.grid,
#   panel.grid.major,
#   panel.grid.minor,
#   panel.grid.major.x,
#   panel.grid.major.y,
#   panel.grid.minor.x,
#   panel.grid.minor.y,
#   panel.ontop,
#   plot.background,
#   plot.title,
#   plot.title.position,
#   plot.subtitle,
#   plot.caption,
#   plot.caption.position,
#   plot.tag,
#   plot.tag.position,
#   plot.margin,
#   strip.background,
#   strip.background.x,
#   strip.background.y,
#   strip.placement,
#   strip.text,
#   strip.text.x,
#   strip.text.y,
#   strip.switch.pad.grid,
#   strip.switch.pad.wrap,
#   ...,
#   complete = FALSE,
#   validate = TRUE
#
